# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  orderserviceapi:
    image: orderserviceapi
    build:
      context: .
      dockerfile: OrderService.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5264:5264
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_HOST=mongodb-container
      - MONGO_PORT=27017
      - MONGO_DATABASE=OrdersDatabase
      - UsersMicroserviceName=usersserviceapi
      - UsersMicroservicePort=4000
    networks:
      - orders-mongo-network
      - ecommerce-network
    depends_on:
      - mongodb-container
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  mongodb-container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d:ro
    networks:
      - orders-mongo-network
  productsserviceapi:
    image: sohelpateldotnet/ecommerce-products-microservices:v1.0
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=mysql-container
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_DATABASE=ecommerceproductsdatabase
      - MYSQL_PORT=3306
    ports:
      - 5000:8080
    networks:
      - products-mysql-network
      - ecommerce-network
    depends_on:
      - mysql-container
  
  mysql-container:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3307:3306
    volumes:
      - ../eCommers.ProductsService/mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - products-mysql-network


  usersserviceapi:
    image: sohelpateldotnet/ecommerce-users-microservice:v1.0
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=eCommersUsers
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
    ports:
      - 4000:8080
    networks:
      - users-postgres-network
      - ecommerce-network
    depends_on:
      - postgres-container
  
  postgres-container:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=eCommersUsers
    ports:
      - 5432:5432
    volumes:
      - ../eCommers/postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - users-postgres-network

networks:
  orders-mongo-network:
    driver: bridge

  products-mysql-network:
    driver: bridge

  users-postgres-network:
    driver: bridge

  ecommerce-network:
    driver: bridge